---
- name: launch azure instance
  hosts: localhost
  tasks:

  - include_vars: vars.yml
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: Test
      name: testvn001
      address_prefixes: "{{ address_prefix }}"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: Test
      name: subnet001
      address_prefix: "{{ address_prefix_subnet }}"
      virtual_network: testvn001

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: Test
      allocation_method: Static
      name: publicip001

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: Test
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001

  - name: Create virtual machine
    register: winvm
    azure_rm_virtualmachine:
      name: "{{ vm_name }}"
      resource_group: Test
      os_type: Windows
      vm_size: Standard_B1s
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      state: present
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2012-R2-Datacenter'
        version: latest

  - azure_rm_publicipaddress_facts:
      resource_group: Test
      name: publicip001
    register: azure_ip

  - add_host:
      hostname: "{{ item.properties.ipAddress }}"
      groups: launched
    with_items: "{{ azure_ip.ansible_facts.azure_publicipaddresses }}"

- hosts: localhost
#  become_user: admin
  roles:
    - key_management
  #  - domain_controller
