---
- hosts: localhost
  roles:
    - security_groups
    - storage_account
    - virtual_network
    - virtual_machines
#    - key_management
#    - credSSP

- hosts: winvm
  roles:
    - domain_controller
