---
- name: enable windows vm cert auth
  shell: az vm run-command invoke -g "{{ resource_group }}" -n "{{ vm_name }}" --command-id RunPowerShellScript --scripts "Set-Item -Path WSMan:\localhost\Service\Auth\Certificate -Value $true"
