---
- name: Install Features
  win_feature:
    name: '{{ item }}'
    include_management_tools: yes
    include_sub_features: yes
    state: present
  with_items:
    - AD-Domain-Services
    - DNS

- name: reboot windows vm
  win_reboot:
    msg: Windows Rebooting
    reboot_timeout: 60
    
