---
- name: ensure windows domain exists
  win_domain:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_netbios_name: "{{ domain_netbios_name }}"
    safe_mode_password: "{{ safe_mode_password }}"
  register: check_domain

- name: reboot windows vm
  win_reboot:
    msg: Windows Rebooting
    reboot_timeout: 600
    post_reboot_delay: 60
  when: check_domain.reboot_required
