---
- name: Add computer to domain
  win_domain_membership:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_admin_user: "{{ user }}"
    domain_admin_password: "{{ password }}"
    state: domain

- name: reboot windows vm
  win_reboot:
    msg: Windows Rebooting
    reboot_timeout: 600
    post_reboot_delay: 60
  when: domain.reboot_required
