---
- azure_rm_publicipaddress_facts:
    resource_group: "{{ resource_group }}"
    name: "{{ public_ip_name }}"
  register: azure_ip

- debug: msg="{{ azure_ip | json_query('ansible_facts.azure_publicipaddresses[*].properties.ipAddress') }}"

- add_host:
    name: "{{ host_name }}"
    hostname: "{{ fqdn }}"
    groups: launched
    ansible_connection: winrm
    ansible_user: "{{ admin_username }}"
    ansible_password: "{{ admin_password }}"
    ansible_port: 5986
  #  ansible_winrm_transport: kerberos
  #  ansible_winrm_cert_pem: "{{ path_to_cert_pem }}"
  #  ansible_winrm_cert_key_pem: "{{ path_to_key_pem }}"
    ansible_winrm_server_cert_validation: ignore
  with_items: "{{ azure_ip | json_query('ansible_facts.azure_publicipaddresses[*].properties.ipAddress') }}"

- name: Create file
  template:
    src: "{{ template_source }}"
    dest: "{{ hosts_dest }}"
  delegate_to: localhost
