---
- name: Create virtual machine
  register: winvm
  azure_rm_virtualmachine:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group }}"
    os_type: Windows
    vm_size: Standard_B1s
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    state: present
    virtual_network_name: "{{virtual_network_name }}"
    subnet_name: "{{ subnet_name }}"
    network_interface_names: "{{ nic_name }}"
    cert_validation_mode: validate
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: '2012-R2-Datacenter'
      version: latest
