---
- name: Add certificate to vm
  shell: az vm secret add --certificate "{{ cert_name }}" --keyvault "{{ vault_name }}" --name "{{ vm_name }}" --resource-group "{{ resource_group }}"
  when: "'domaincontroller' not in cert.stdout"
