---
- name: create instance of key vault
  azure_rm_keyvault:
    resource_group: "{{ resource_group }}"
    vault_name: "{{ vault_name }}"
    enabled_for_deployment: yes
    vault_tenant: "{{ vault_tenant_ID }}"
    sku:
      name: standard
    access_policies:
      - tenant_id: "{{ vault_tenant_ID }}"
        object_id: "{{ object_ID }}"
        keys:
          - get
          - list
          - create
          - delete
          - import
          - update
          - backup
          - restore
          - recover
          - purge
          - sign
          - verify
          - encrypt
        certificates:
          - get
          - list
          - delete
          - create
          - import
          - update
          - managecontacts
          - getissuers
          - listissuers
          - setissuers
          - deleteissuers
          - manageissuers
          - recover
          - purge  
