---
- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ subnet_name }}"
    address_prefix: "{{ address_prefix_subnet }}"
    virtual_network: "{{ virtual_network_name }}"
