---
- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ virtual_network_name }}"
    address_prefixes: "{{ address_prefix }}"
#    dns_servers: "{{ dns_address }}"
