---
- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ nic_name }}"
    virtual_network: "{{ virtual_network_name }}"
    subnet: "{{ subnet_name }}"
    public_ip_name: "{{ public_ip_name }}"
    security_group: "{{ security_group_name }}"
